# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  # Main
  - name: Home
    url: /#top
    weight: 10
  - name: About
    weight: 20
    url: about/
  - name: Mission
    url: /#mission
    weight: 30
  - name: Activities
    url: /#activities
    weight: 40

  # Updates
  - name: News 
    weight: 40
    url: news/
  - name: Blog
    weight: 45
    url:  blog/

  # Projects
  - name: Brownbag Series
    weight: 50
    url: brownbag/
  - name: Publications
    weight: 60
    url: publications/

  # Team
  - name: Team
    weight: 100
    url: authors/
