# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  # Main
  - name: Home
    url: /#top
    weight: 10
  - name: About
    weight: 20
    url: /#about
  - name: Mission
    url: /#mission
    weight: 30

  # Updates
  - name: News 
    weight: 40
    url: news/

  # Activities
  - name: Activities
    weight: 50
    hasChildren: true

  - parent: Activities
    name: Regular Meetings
    weight: 100
    url:  meetings/
  - parent: Activities
    name: Events
    weight: 110
    url:  events/
  - parent: Activities
    name: Brownbag
    weight: 120
    url:  brownbag/

  # Resources
  - name: Resources
    weight: 60
    hasChildren: true

  - parent: Resources
    name: Blog
    weight: 100
    url: blog/
  - parent: Resources
    name: Publications
    weight: 110
    url: publications/
